#!/usr/bin/env node

/**
 * destroy.mjs
 * 
 * Safely tears down deployed Cloudflare services:
 *   --api : Deletes Cloudflare Worker
 *   --web : Deletes Cloudflare Pages project
 *   (default / --all) : Deletes both and cleans up apps/web/.env.local
 */

import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as readline from 'node:readline';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const webEnvPath = path.resolve(rootDir, 'apps', 'web', '.env.local');

const args = process.argv.slice(2);
const isForce = args.includes('--force') || args.includes('-y') || args.includes('--yes');
const isApiOnly = args.includes('--api') || args.includes('--app') || args.includes('--worker');
const isWebOnly = args.includes('--web') || args.includes('--pages');
const destroyAll = !isApiOnly && !isWebOnly;

// 1. Environment Loading (.env & .env.local)
function loadEnv() {
  for (const file of ['.env', '.env.local']) {
    const fp = path.resolve(rootDir, file);
    if (!fs.existsSync(fp)) continue;
    if (typeof process.loadEnvFile === 'function') {
      try { process.loadEnvFile(fp); continue; } catch {}
    }
    const lines = fs.readFileSync(fp, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const idx = trimmed.indexOf('=');
      if (idx === -1) continue;
      const key = trimmed.slice(0, idx).trim();
      const val = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
      if (key && !(key in process.env)) process.env[key] = val;
    }
  }
}

loadEnv();

function runCmd(cmd, options = {}) {
  return execSync(cmd, {
    encoding: 'utf8',
    ...options,
    env: { ...process.env, ...(options.env || {}) },
  });
}

async function confirmTeardown() {
  if (isForce || !process.stdin.isTTY) return true;

  const targets = [];
  if (destroyAll || isApiOnly) targets.push('Cloudflare Worker (API)');
  if (destroyAll || isWebOnly) targets.push('Cloudflare Pages (Web UI)');

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(
      `⚠️  Are you sure you want to DESTROY [${targets.join(', ')}]? (y/N): `,
      (answer) => {
        rl.close();
        resolve(answer.trim().toLowerCase() === 'y' || answer.trim().toLowerCase() === 'yes');
      }
    );
  });
}

async function main() {
  console.log('🗑️  my-ip-info Cloudflare Teardown Utility');
  console.log('─'.repeat(60));

  const proceed = await confirmTeardown();
  if (!proceed) {
    console.log('Teardown cancelled by user.');
    process.exit(0);
  }

  const workerAccountId = process.env.CLOUDFLARE_WORKER_ACCOUNT_ID || process.env.CLOUDFLARE_ACCOUNT_ID;
  const pagesAccountId = process.env.CLOUDFLARE_PAGES_ACCOUNT_ID || process.env.CLOUDFLARE_ACCOUNT_ID;

  // 1. Destroy Cloudflare Worker
  if (destroyAll || isApiOnly) {
    console.log('\n🧹 Destroying Cloudflare Worker API...');
    const cfDir = path.resolve(rootDir, 'apps', 'server-cloudflare');
    try {
      const workerName = process.env.CLOUDFLARE_WORKER_NAME || 'my-ip-info';
      console.log(`   Deleting Worker '${workerName}'${workerAccountId ? ` (Account ID: ${workerAccountId})` : ''}...`);
      const workerEnv = workerAccountId ? { CLOUDFLARE_ACCOUNT_ID: workerAccountId } : {};
      const output = runCmd(`npx wrangler delete ${workerName} --force`, { cwd: cfDir, env: workerEnv });
      console.log(output);
      console.log(`✅ Cloudflare Worker '${workerName}' removed.`);
    } catch (err) {
      console.warn('⚠️ Could not delete Cloudflare Worker (it may not exist or wrangler is unauthenticated).');
      if (err.stdout) console.log(err.stdout);
    }
  }

  // 2. Destroy Cloudflare Pages
  if (destroyAll || isWebOnly) {
    console.log('\n🧹 Destroying Cloudflare Pages Web Project...');
    const projectName = process.env.CLOUDFLARE_PAGES_PROJECT_NAME || 'my-ip-info';
    try {
      console.log(`   Deleting Pages project '${projectName}'${pagesAccountId ? ` (Account ID: ${pagesAccountId})` : ''}...`);
      const pagesEnv = pagesAccountId ? { CLOUDFLARE_ACCOUNT_ID: pagesAccountId } : {};
      const output = runCmd(`npx wrangler pages project delete ${projectName} --yes`, { cwd: rootDir, env: pagesEnv });
      console.log(output);
      console.log(`✅ Cloudflare Pages project '${projectName}' deleted.`);
    } catch (err) {
      console.warn(`⚠️ Could not delete Cloudflare Pages project '${projectName}' (it may not exist).`);
      if (err.stdout) console.log(err.stdout);
    }
  }

  // Clean apps/web/.env.local if API was destroyed
  if (destroyAll || isApiOnly) {
    if (fs.existsSync(webEnvPath)) {
      const envLines = [
        '# Auto-generated by destroy.mjs',
        `# Last updated: ${new Date().toISOString()}`,
        '',
        'VITE_CLOUDFLARE_URL=',
        '',
      ];
      fs.writeFileSync(webEnvPath, envLines.join('\n'), 'utf8');
      console.log('\n✨ Cleared VITE_CLOUDFLARE_URL in apps/web/.env.local');
    }
  }

  console.log('\n🎉 Teardown complete!\n');
}

main().catch((err) => {
  console.error('Fatal teardown error:', err);
  process.exit(1);
});
